config/routes.rb
Rails.application.routes.draw do
  

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'home' => 'static_pages#home'
  
  resources :posts, only: [:create, :destroy]
  resources :users do 
    member do 
      get :followers ,:following 
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new , :create, :edit, :update]
  resources :relationships, only: [:create,:destroy ]

    root "static_pages#home"
    

end

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
  <p>This form contains <%= pluralize(object.errors.count, 'error') %></p>
  <ul>  
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/shared/_feed_partial.html.erb
<% if @feed_items.any? %> 
  <ol class='posts' id="feed">
    <%= render @feed_items %>
    <!-- Since each item in collection belongs to class `Post`, Rails will look for a partial with the corresponding name in the view directory.-->
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <%= render 'shared/error_message', object: f.object %>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content , placeholder: 'Compose new post..' %>
  </div>
  <div class="field">
    <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %> 
  </div>
  <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>
<script type="text/javascript">
  $('#post_picture').on('change',function(){
    var size_in_megabytes = this.files[0].size/1024/1024;
    if(size_in_megabytes > 5){
      alert("Maximum file size is 5MB. Please choose another file.");
    }
   
  });
</script>

app/views/shared/_user_info.html.erb
<%  @user ||= current_user %> 
<%= link_to gravatar_for(@user, 'none', size: 80), @user %>
<span class="user"><%= @user.name %></span></br>
<span class="profile_link"><%= link_to 'View my profile', @user %></span></br>
<span class="edit_link"><%= link_to 'Edit User', edit_user_path(@user) %></span>
<span class="post_count"><%= pluralize(@user.posts.count,'post')%></span>

<%= render 'shared/user_stat' %>

app/views/shared/_user_stat.html.erb
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
        Following 
        <strong id="following" class="stat">
           <%= @user.following.count %>
        </strong>
    </a>
    <a href="<%= followers_user_path(@user)%>">
        Follower 
        <strong id="followers" class="stat">
            <%= @user.followers.count%>
        </strong>
    </a>
</div>