config/routes.rb
Rails.application.routes.draw do
  

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'home' => 'static_pages#home'
  
  resources :posts, only: [:create, :destroy]
  resources :users do 
    member do 
      get :followers ,:following 
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new , :create, :edit, :update]
  resources :relationships, only: [:create,:destroy ]

    root "static_pages#home"
    

end

app/views/layouts/_footer.html.erb
<P>Powered by Ruby on Rails</P>

app/views/layouts/_header.html.erb
<header class="marker">
  <div class="nav-container marker">
    <nav>
        <ul class="center">
            <li><%= link_to 'Home',root_path %></li>
            <li><%= link_to 'About' %></li>
            
            <% if logged_in?%>
              <li><%= link_to 'Logout', logout_path, method: :delete %></li>
              <li><%= link_to 'Users', users_path %></li>
              <li class="drop-down">Account
              <ul class="marker">
                <li><%= link_to 'Profile', user_path(current_user) %></li>
                <li><%= link_to 'Setting' %></li>
              </ul>
              </li>
            <% else %>
              <li><%= link_to 'Login', login_path %></li>
            <% end %>
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title(yield :title)%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class='main-content'>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>